learning_templates/basic_app/urls.py
from django.conf.urls import url
from .import views

app_name='basic_app' 

#template tagging
urlpatterns=[
	url(r'^relative/$', views.relative,name='relative'),
	url(r'^other/', views.other,name='other'),
]

learning_templates/learning_templates/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views

urlpatterns = [
	url(r'^$', views.index,name='index'),
	url(r'^basic_app/', include('basic_app.urls')),
    url(r'^admin/', admin.site.urls),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	context_dict={'text':'HELLO WORLD','num':1323}
	return render(request,'basic_app/index.html',context_dict)

def relative(request):
	return render(request,'basic_app/relative_url.html')

def other(request):
	return render(request,'basic_app/other.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>base</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
<nav class='navbar navbar-dafault navbar-static-top'>
	<ul class="nav navbar-nav">
		<li><a href="{% url 'index' %}" class="navbar-brand">Home</a></li>
		<li><a href="{% url 'basic_app:other' %}" class="navbar-brand">Other</a> </li>
		<li><a href="{% url 'basic_app:relative' %}" class="navbar-brand">Relative</a></li>
	</ul>
</nav>
<div class="container">
	{% block body_block %}

	{% endblock %}
</div>
</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% load my_extra %}
{% block body_block%}
<div class="jumbotron">
	<h1>This is a index page</h1>
	<h2>welcome to index page..</h2>
	<h3>{{text|chait:'HELLO'}}</h3>
	<h3>{{text|small}}</h3>
	<h3>{{num|add:'23434'}}</h3>
</div>
{% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
<div class="jumbotron">
	<h1>This is a other page</h1>
	<h2>welcome to other page..</h2>
</div>
{% endblock %}

learning_templates/templates/basic_app/relative_url.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
	<div class="jumbotron">
		<h1>This is relative url page</h1>
		<a href="{% url 'basic_app:other' %}">Go to other page |</a>
		<a href="{% url 'admin:index' %}">Go to admin page |</a>
		<a href="{% url 'index' %}">Go to index page</a>
	</div>
{% endblock %}